APPLY_FIXES: none
PRINT_ALL_FILES: false
SHOW_ELAPSED_TIME: true

ENABLE_LINTERS:
  - MARKDOWN_MARKDOWNLINT
  - YAML_YAMLLINT
  - PYTHON_RUFF
  - CMAKE_CMAKE_LINT
  - BASH_SHELLCHECK

MARKDOWN_MARKDOWNLINT_CONFIG_FILE: .markdownlint.yml

YAML_YAMLLINT_CONFIG_FILE: .yamllint.yml

FILTER_REGEX_EXCLUDE: '(build/|\.conan2/|test_package/build/)'
